# This file is derived from a GitLab template.
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Pages/Hugo.gitlab-ci.yml

variables:
  GIT_SUBMODULE_STRATEGY: none

stages:
  - build
  - deploy

update_website:
  stage: build
  image: python:latest
  script:
    - python -m	pip install -r requirements.txt
    - python scripts/ggi_deploy_gitlab.py -a -b -d -p --random-demo
    - python scripts/ggi_update_website_gitlab.py
    - head web/config.toml
  cache:
    key: "$CI_COMMIT_SHORT_SHA"
    paths:
      - ./web

pages:
  stage: deploy
  # All available Hugo versions are listed here:
  # https://gitlab.com/pages/hugo/container_registry
  image: registry.gitlab.com/pages/hugo/hugo_extended:latest
  script:
    - cd web && hugo && cd -
    - mv -v web/public .
  cache:
    key: "$CI_COMMIT_SHORT_SHA"
    paths:
      - ./web
  artifacts:
    paths:
      - public/
  only:
    - main
